config/routes.rb
Logistic::Application.routes.draw do

  resources :setting_mains, except: :index


  resources :brands


  resources :areas

  resources :purchase_orders do
    member do
      put :canceled
    end
    collection do
      get :quotation_list
    end
  end

  get "site/index"

  resources :quotations do
    resource :purchase_orders
    member do
      get :fill_costs
      put :save_fill_costs
      get :toggle
      get :status_change
    end
    collection do
      get :compare
      get :pending_requeriment
    end
  end

  resources :providers

  resources :movement_items, only: [:update, :index]

  resources :movements, only: [:index, :show, :destroy] do
    member do
      get :print
    end
    collection do
      get :new_get_out_purchase_order
      get :new_purchase
      get :purchase_orders
      get :pending_incoming_purchases
      post :create_get_out_purchase_order
      post :create_purchase
      get :new_incoming
      post :create_incoming
      # get :new_get_out
      post :create_get_out
      get :pending_input_notes
    end
  end

  resources :requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :serv_requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :products
  resources :groups
  resources :sub_groups
  resources :categories
  resources :brands
  resources :input_notes

  resources :ware_houses do
    get 'new_get_out' => 'movements#new_get_out'
    get 'initial' => 'movements#initial'
    get 'physical' => 'product_ware_houses#index'
    collection do
      get :own
      get :kardex
    end
  end

  resources :product_ware_houses, only: [:index, :update] do
    collection do
      put :update_multiple
    end
  end

  devise_for :users

  resources :users

  root :to => 'site#index'

  get 'dynamic_groups_by_type' => 'javascripts#dynamic_groups_by_type'
  get 'product_by_ware_house' => 'javascripts#product_by_ware_house'
  get 'products_by_ware_house' => 'javascripts#products_by_ware_house'
  get 'dynamic_sub_groups' => 'javascripts#dynamic_sub_groups'
  get 'dynamic_categories' => 'javascripts#dynamic_categories'
  get 'dynamic_products' => 'javascripts#dynamic_products'
  get 'dynamic_brands_by_group' => 'javascripts#dynamic_brands_by_group'
  get 'dynamic_brands_by_sub_group' => 'javascripts#dynamic_brands_by_sub_group'

  get 'load_other_products_from_category' => 'javascripts#load_other_products_from_category'
  get 'load_other_categories_from_sub_group' => 'javascripts#load_other_categories_from_sub_group'
  get 'load_other_sub_groups_from_group' => 'javascripts#load_other_sub_groups_from_group'
  get 'load_other_brands_from_sub_group' => 'javascripts#load_other_brands_from_sub_group'

  get 'get_product' => 'javascripts#get_product'

end

app/models/movement.rb
class Movement < ActiveRecord::Base
  CANCELED = 1

  STATUS_TYPES = {
    CANCELED => "Anulado"
  }

  FACTURA     = 1
  BOLETA      = 2
  GUIA        = 3

  DOCUMENT_TYPES = {
    FACTURA => "Factura",
    BOLETA     => "Boleta",
    GUIA      => "Guia"
  }

  belongs_to :provider
  belongs_to :ware_house
  belongs_to :purchase_order
  belongs_to :input_note, dependent: :destroy
  belongs_to :movement_type
  belongs_to :emisor, class_name: 'User'
  # belongs_to :receiver, class_name: 'User'
  has_many :movement_items, dependent: :destroy, inverse_of: :movement

  attr_accessor :product_id
  accepts_nested_attributes_for :movement_items, allow_destroy: true
  attr_accessible :emisor_id, :ware_house_id, :movement_type_id, :provider_id, :status, :date, :movement_items_attributes, :receiver,
                 :invoice_date, :observation, :serial, :document_type, :purchase_order_id, :doc_ref, :invoice_number, :created_at
  # :price_unit, :quantity, :product_id,
  validates :emisor_id, :ware_house_id, :movement_type_id, presence: true
  #:quantity, :product_id,
  # before_create :set_price, if: Proc.new{|m| m.price_unit.nil?}
  after_create :generate_name
  before_destroy :check_dispatched_movements
  # after_create :update_current_stock
  # after_create :calculate_average_cost

  def generate_items_from_purchase_order
    purchase_order.purchase_details.each do |item|
      if item.pending_quantity > 0
        movement_items.build(
          :purchase_detail_id => item.id,
          :product_id => item.product_id,
          :quantity => item.pending_quantity,
          :price_unit => item.price_unit,
          :price_total => item.price_total,
          :brand_id => item.brand_id,
          :model => item.model,
          :detail => item.detail
        )
      end
    end
  end

  def generate_items_get_out
    purchase_order.purchase_details.each do |item|
      if item.pending_quantity < item.quantity#se ha entregado algo
        movement_items.build(
          :purchase_detail_id => item.id,
          :product_id => item.product_id,
          :quantity => (item.quantity - item.pending_quantity) - item.outgoing,
          :price_unit => item.price_unit,
          :price_total => item.price_total,
          :brand_id => item.brand_id,
          :model => item.model,
          :detail => item.detail
        )
      end
    end
  end

  def document_text
    DOCUMENT_TYPES[self.document_type]
  end

  def type_text
    TYPES[self.movement_type_id]
  end

  # def operation_type_name
  #   if input_note_id.present?
  #     input_note.movement_type.name
  #   else
  #     purchase_order.movement_type.name
  #   end
  # end

  def operation_number #numero de operacion de nota de entrada u orden de compra
    if purchase_order_id.present?
      purchase_order.name
    else
      name
    end
  end

  private

  def generate_name
    new_name = Movement.maximum(:name) || '00000000'
    self.update_column(:name, new_name.next)
  end

  def check_dispatched_movements
    if movement_type_id == 2
      if purchase_order.movements.pluck(:movement_type_id).uniq.include?(3)
        errors.add(:base, "No se puede eliminar porque la orden de compra tiene movimientos de salida")
      end
    end
    errors.blank?
  end
end

app/models/movement_type.rb
class MovementType < ActiveRecord::Base
  attr_accessible :name, :signal, :type_process
  scope :incoming, ->(){ where("signal != ? and id != ? ", -1, 2) }
  scope :incoming_purchase, ->(){ where("id = ?  ", 2) }
  scope :get_out, ->(){ where(signal: -1) }
  scope :get_out_normal, ->(){ where("signal = ? and id != ? ", -1, 3 ) }
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  load_and_authorize_resource

  def index
    @ware_house_ids = current_user.filter_ware_houses.map(&:id)
    @search = if current_user.super_admin?
      @movements.includes(:movement_type, :ware_house).order('id DESC').search(params[:search])
    else current_user.responsible_ware_house?
      @movements.includes(:movement_type, :ware_house).where('ware_house_id in (?)', @ware_house_ids).order('id DESC').search(params[:search])
    end
    @movements.includes(:movement_type, :ware_house).where(ware_house_id: current_user.area.ware_houses.pluck(:id)).order('id DESC').search(params[:search])
    @movements = @search.page(params[:page]).per(15)
    @movement = Movement.new
    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def print
    respond_to do |format|
      format.pdf{
        render pdf: "file_name", wkhtmltopdf: '/usr/bin/wkhtmltopdf', orientation: 'landscape', page_size: 'A4', margin: {top: 0, bottom: 0, left: 0, right: 0}, lowquality: false
      }
    end
  end

  def new_purchase
    @purchase_order = PurchaseOrder.find(params[:purchase_order_id])
    @movement = @purchase_order.movements.new(ware_house_id: @purchase_order.quotation.requeriment.ware_house.id)
    @movement.generate_items_from_purchase_order
    respond_to do |format|
      format.html
    end
  end

  def purchase_orders
    statuses = [PurchaseOrder::SENT, PurchaseOrder::PARTIAL_CLOCKED]
    @search = PurchaseOrder.where("type_order= ?", 1).where(:status => statuses).order('id desc').search(params[:search])
    @purchase_orders = @search.page(params[:page]).per(15)
    respond_to do |format|
      format.html
    end
  end

  def pending_incoming_purchases
    @search = PurchaseOrder.pending_incoming_purchases.order('id desc').search(params[:search])
    @purchase_orders = @search.page(params[:page])
    respond_to do |format|
      format.html
    end
  end

  def create_purchase
    purchase_order = PurchaseOrder.find(params[:movement][:purchase_order_id])
    attributes = purchase_order.attributes.slice("provider_id").merge(params[:movement])
    @movement = Movement.new(attributes)
    @movement.receiver_id = @movement.ware_house.responsible_id if @movement.ware_house_id
    @movement.emisor_id = current_user.id
    @purchase_orders = PurchaseOrder.all
    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: t(:data_created) }
      else
        format.html { render action: "new_purchase" }
      end
    end
  end

  def new_incoming
    # @groups = Group.where("type_group = ?", 1).order('description')#bienes por defecto
    @input_note = InputNote.new
    @input_note.input_note_details.build
    @input_note.type_input_note = 1
    respond_to do |format|
      format.html
    end
  end

  def initial
    @ware_house = WareHouse.find(params[:ware_house_id])
    @search =  @ware_house.movements.where(movement_type_id: 1).includes(:movement_type).order('id DESC').search(params[:search])
    @movements = @search.page(params[:page])
    respond_to do |format|
      format.html
    end
  end

  def create_incoming
    @input_note = InputNote.new(params[:input_note])
    @input_note.emisor_id = current_user.id
    respond_to do |format|
      if @input_note.save
        @movement = @input_note.new_movement
        @movement.save
        if @input_note.movement_type_id == 1 #si es saldo incial forzar a que sea el primer movimiento
          @input_note.update_attributes(created_at: Date.today.beginning_of_year)
          @movement.update_attributes(created_at: Date.today.beginning_of_year)
          @movement.movement_items.update_all(created_at: Date.today.beginning_of_year)
        end
        format.html { redirect_to @movement, notice: t(:data_created) }
      else
        format.html { render action: "new_incoming" }
      end
    end
  end

  def new_get_out
    @ware_house = WareHouse.find params[:ware_house_id]
    @products = @ware_house.products
    @movement = Movement.new(ware_house_id: @ware_house.id)
    respond_to do |format|
      format.html
    end
  end

  def new_get_out_purchase_order
    purchase_order = PurchaseOrder.find(params[:purchase_order_id])
    @movement = Movement.new :purchase_order_id => purchase_order.id, :ware_house_id => purchase_order.quotation.requeriment.ware_house.id
    @movement.generate_items_get_out

    respond_to do |format|
      format.html
    end
  end

  def create_get_out
    purchase_order = PurchaseOrder.find(params[:movement][:purchase_order_id])
    attributes = purchase_order.attributes.slice("provider_id").merge(params[:movement])
    @movement = Movement.new(attributes)
    @movement.emisor_id = current_user.id
    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: t(:data_created) }
      else
        @products = @movement.ware_house.products
        format.html { redirect_to ware_house_new_get_out_path(@movement.ware_house.id), alert: "Elija el tipo de movimiento" }
      end
    end
  end

  def create_get_out_purchase_order
    @movement = Movement.new(params[:movement])
    @movement.receiver_id = @movement.ware_house.responsible_id if @movement.ware_house_id
    @movement.emisor_id = current_user.id
    @purchase_orders = PurchaseOrder.all
    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: t(:data_created) }
      else
        format.html { render action: "new_get_out_purchase_order" }
      end
    end
  end

  def destroy
    message = @movement.errors[:base].first unless @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, :notice => message }
    end
  end

  def pending_input_notes
    @search = InputNote.pending_input_notes.order('id desc').search(params[:search])
    @input_notes = @search.page(params[:page]).per(15)
  end
end

app/helpers/movements_helper.rb
module MovementsHelper
  def can_destroy_movement?(movement)
    if movement.movement_type.id == 2
      (can? :destroy, movement) && movement.purchase_order.without_outgoing?
    else
      can? :destroy, movement
    end
  end
end

app/views/movements/_form_get_out_purchase_order.html.erb
<div class="span12">
  <div class="span4"><strong>Nro Orden Compra:</strong></div>
  <div class="span8"><%= link_to @movement.purchase_order.name, @movement.purchase_order %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Proveedor:</strong></div>
  <div class="span8"><%= @movement.purchase_order.provider.name %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Almacen:</strong></div>
  <div class="span8"><%= @movement.ware_house.name %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Fecha creacion orden de compra:</strong></div>
  <div class="span8"><%= l(@movement.purchase_order.created_at) %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Área destino:</strong></div>
  <div class="span8"><%= @movement.purchase_order.quotation.requeriment.area.name %></div>
</div>

<%= simple_form_for(@movement, url: create_get_out_purchase_order_movements_url, :html => {:class => '', :novalidate => false }) do |f| %>
  <%= f.error_notification %>

  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Cantidad disponible</th>
        <th>Cantidad enviada</th>
        <th>Precio Unit.</th>
        <th>Precio Total</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Detalle</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @movement.movement_items.each do |item| %>
        <%= f.fields_for :movement_items, item do |item_builder| %>
          <tr>
            <td>
              <%= item_builder.hidden_field :purchase_detail_id %>
              <%= item_builder.hidden_field :product_id %>
              <%= item_builder.hidden_field :price_unit %>
              <%= item_builder.hidden_field :brand_id %>
              <%= item_builder.hidden_field :model %>
              <%= item_builder.hidden_field :detail %>
              <%= item.product.description %></td>
            <td><%= (item.quantity) %></td>
            <td><%= item_builder.text_field :quantity, type: :number, max: item.quantity, min: 0, class: 'span12' %></td>
            <td><%= number_to_currency(item.price_unit) %></td>
            <td><%= number_to_currency(item.price_total) %></td>
            <td><%= item.brand.try(:description) %></td>
            <td><%= item.model %></td>
            <td><%= item.detail %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="form-inputs">
    <div class="span12">
      <%= f.association :movement_type, collection: MovementType.get_out, selected: 3, disabled: true, input_html: {class: 'span4'} %>
      <div class="hidden">
        <%= f.association :movement_type, collection: MovementType.get_out, selected: 3, input_html: {class: 'span4'} %>
      </div>
    </div>
    <%= f.hidden_field :purchase_order_id, :value => @movement.purchase_order.id %>
    <%= f.hidden_field :ware_house_id, :value => @movement.purchase_order.quotation.requeriment.ware_house.id %>

    <%= f.input :receiver %>
    <div class="row-fluid">
      <div class="span12"><%=f.input :observation, input_html: {class: 'span12', rows: 5}%></div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movements/_form_purchase.html.erb
<div class="span12">
  <div class="span4"><strong>Nro Orden Compra:</strong></div>
  <div class="span8"><%= link_to @movement.purchase_order.name, @movement.purchase_order %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Proveedor:</strong></div>
  <div class="span8"><%= @movement.purchase_order.provider.name %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Almacen:</strong></div>
  <div class="span8"><%= @movement.ware_house.name %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Fecha creacion orden de compra:</strong></div>
  <div class="span8"><%= l(@movement.purchase_order.created_at) %></div>
</div>

<div class="span12">
  <div class="span4"><strong>Área destino:</strong></div>
  <div class="span8"><%= @movement.purchase_order.quotation.requeriment.area.name %></div>
</div>

<%= simple_form_for(@movement, url: create_purchase_movements_url, :html => {:class => '', :novalidate => false}) do |f| %>
  <%= f.error_notification %>

  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Cantidad total</th>
        <th>Cantidad ingresada</th>
        <th>Precio Unit.</th>
        <th>Precio Total</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Detalle</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @movement.movement_items.each do |item| %>
        <%= f.fields_for :movement_items, item do |item_builder| %>
          <tr>
            <td>
              <%= item_builder.hidden_field :purchase_detail_id %>
              <%= item_builder.hidden_field :product_id %>
              <%= item_builder.hidden_field :price_unit %>
              <%= item_builder.hidden_field :model %>
              <%= item_builder.hidden_field :brand_id %>
              <%= item_builder.hidden_field :detail %>
              <%= item.product.description %></td>

            <td><%= item.purchase_detail.quantity %></td>
            <td><%= item_builder.text_field :quantity, type: :number, max: item.quantity, min: 0, class: 'span8' %></td>
            <td><%= number_to_currency(item.price_unit) %></td>
            <td><%= number_to_currency(item.price_total) %></td>
            <td><%= item.brand.try(:description) %></td>
            <td><%= item.model %></td>
            <td><%= item.detail %></td>
            <td></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="form-inputs">
    <div class="row-fluid">
      <div class="span12">
        <%= f.association :movement_type, collection: MovementType.incoming_purchase, selected: 2, disabled: true, input_html: {class: 'span4'} %>
        <div class="hidden">
          <%= f.association :movement_type, collection: MovementType.incoming_purchase, selected: 2, input_html: {class: 'span4'} %>
        </div>
      </div>
    </div>


    <div class="row-fluid">
      <div class="span6"><%= f.input :document_type, collection: [["- Tipo de documento - ", ''], ["Factura", 1], ["Boleta", 2], ["Guia de remision", 3]], default: 1 %></div>
    </div>
    <div class="row-fluid">
      <div class="span6"><%= f.input :invoice_number, label: "Nro documento" %></div>
    </div>
    <div class="row-fluid"><div class="span12"><%= f.input :invoice_date, as: :datepicker %></div></div>
    <%= f.hidden_field :purchase_order_id, :value => @movement.purchase_order.id %>
    <%= f.hidden_field :ware_house_id, :value => @movement.purchase_order.quotation.requeriment.ware_house.id %>
    <div class="row-fluid">
      <div class="span12"><%= f.input :serial %></div>
    </div>
    <div class="row-fluid">
      <div class="span12"><%=f.input :observation, input_html: {class: 'span12', rows: 5}%></div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movements/_input_note_detail_fields.html.erb
<tr class='row_item fields'>
  <td><%= f.link_to_remove '<i class="icon-minus"></i>'.html_safe %></td>
  <td>
    <%= f.input :group_id, collection: Group.by_type_group(1).map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_group'}, prompt: '- Seleccione una opcion -' %>
  </td>
  <td>
    <%= f.input :sub_group_id, collection: SubGroup.by_group(f.object.group_id).map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_sub_group'} %>
  </td>
  <td>
    <%= f.input :category_id, collection: Category.by_sub_group(f.object.sub_group_id).map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_category'} %>
  </td>
  <td>
    <%= f.association :product, collection: Product.by_category(f.object.category_id).map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_product'} %>
  </td>
	<td><%= f.input :quantity, label: false, wrapper: false, input_html: {class: 'span12'} %></td>
	<td><%= f.input :price_unit, label: false, wrapper: false, input_html: {step: "0.01"} %></td>

  <td>
    <%= f.association :brand, collection: Brand.all.map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_brand'} %>
  </td>

  <td><%=f.input :model, label: false, wrapper: false%></td>

  <td><%= f.input :detail, label: false, wrapper: false, input_html: {cols: 10, rows: 2} %></td>

  <div class="hidden">
    <%= f.input :price_total, label: false, wrapper: false %>
  </div>
</tr>

app/views/movements/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Acciones</li>
      <%=nav_link('Movimientos', movements_path)%>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/movements/_sidebar_in.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Acciones</li>
      <%=nav_link('Ingreso Ord. Compra', purchase_orders_movements_path) if can? :purchase_orders, Movement%>
      <%=nav_link('Nota de Entrada', new_incoming_movements_path) if can? :new_incoming, Movement%>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/movements/edit.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3 class='text-center'>Actualizar movimiento</h3>
	<%= render 'form' %>
</div>

app/views/movements/new.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3 class='text'>Nuevo movimiento</h3>
	<%= render 'form' %>
</div>

app/views/movements/new_incoming.html.erb
<%=render 'movements/sidebar_in'%>
<div class="span9">
	<h3 class='text-center'>Nuevo ingreso</h3>
	<%= render 'form_incoming' %>
</div>

app/views/movements/pending_incoming_purchases.html.erb
<%=render 'movements/sidebar_out'%>
<div class="span9">
	<h3 class='text-center'>Salida de orden de compras</h3>

  <%=simple_form_for(@search, html: {class: 'form-search' }) do |f|%>
    <%= f.label :name_contains, "Numero" %>
    <%= f.text_field :name_contains, class: 'search-query'%>
    <button type="submit" class="btn">Buscar</button>
  <%end%>

  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Orden de Compra</th>
        <th>Estado</th>
        <th>Cotizacíon</th>
        <th>Requerimiento</th>
        <th>Proveedor</th>
        <th>Fecha</th>
        <th>Total</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @purchase_orders.each do |purchase_order| %>
        <% if purchase_order.quotation.requeriment.area.id == current_user.area_id  || current_user.super_admin? %>
          <tr>
            <% name_type = "Salida " if purchase_order.status == PurchaseOrder::PARTIAL_CLOCKED %>
            <td><%= purchase_order.name %></td>
            <td><%= "#{name_type}#{purchase_order.status_text}" %></td>
            <td><%= link_to purchase_order.quotation.name, quotation_path(purchase_order.quotation.id) %></td>
            <td><%= link_to purchase_order.quotation.requeriment.name, requeriment_path(purchase_order.quotation.requeriment.id) %></td>
            <td><%= purchase_order.provider.name %></td>
            <td><%= l(purchase_order.created_at, :format => :default) %></td>
            <td><%= number_to_currency(purchase_order.total) %></td>
            <td><%= show_link purchase_order %></td>
            <td><%= link_to 'salida', new_get_out_purchase_order_movements_path(:purchase_order_id => purchase_order.id) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @purchase_orders %>
</div>

app/views/movements/pending_input_notes.html.erb
<%= render 'sidebar' %>
<div class="span9">
	<h3 class='text-center'>Pedidos de notas de entrada</h3>

  <%= simple_form_for(@search, html: {class: 'form-search' }) do |f|%>
    <%= f.label :name_contains, "Numero" %>
    <%= f.text_field :name_contains, class: 'search-query'%>
    <button type="submit" class="btn">Buscar</button>
  <% end %>

  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Nota de entrada</th>
        <th>Proveedor</th>
        <th>Fecha de creación</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @input_notes.each do |input_note| %>
        <tr>
          <td><%= link_to input_note.name, new_get_out_movements_path(:input_note_id => input_note.id) %></td>
          <td><%= input_note.provider.try(:name) || '-' %></td>
          <td><%= l(input_note.created_at) %></td>
          <td><%= number_to_currency(input_note.total) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%=paginate @input_notes %>
</div>

app/views/movements/purchase_orders.html.erb
<%=render 'movements/sidebar_in'%>
<div class="span9">
	<h3 class='text-center'>Nuevo ingreso de compras</h3>

  <%= simple_form_for(@search, html: {class: 'form-search' }) do |f| %>
    <%= f.label :name_contains, "Numero" %>
    <%= f.text_field :name_contains, class: 'search-query'%>
    <button type="submit" class="btn">Buscar</button>
  <% end %>

  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Orden de Compra</th>
        <th>Estado</th>
        <th>Cotizacíon</th>
        <th>Requerimiento</th>
        <th>Proveedor</th>
        <th>Fecha de orden de compra</th>
        <th>Total</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @purchase_orders.each do |purchase_order| %>
        <% if purchase_order.quotation.requeriment.area.id == current_user.area_id  || current_user.super_admin? %>
          <tr>
            <% name_type = "Ingreso " if purchase_order.status == PurchaseOrder::PARTIAL_CLOCKED %>
            <td><%= purchase_order.name %></td>
            <td><%= "#{name_type}#{purchase_order.status_text}" %></td>
            <td><%= link_to purchase_order.quotation.name, quotation_path(purchase_order.quotation.id) %></td>
            <td><%= link_to purchase_order.quotation.requeriment.name, requeriment_path(purchase_order.quotation.requeriment.id) %></td>
            <td><%= purchase_order.provider.name %></td>
            <td><%= l(purchase_order.created_at) %></td>
            <td><%= number_to_currency(purchase_order.total) %></td>
            <td><%= show_link purchase_order %></td>
            <td><%= link_to 'Recepcion', new_purchase_movements_path(:purchase_order_id => purchase_order.id) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @purchase_orders %>
</div>

app/views/movements/show.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<p id="notice"><%= notice %></p>

	<%= render @movement %>

	<%= print_button @movement %>
	<%#= destroy_button @movement %>
</div>