config/routes.rb
Logistic::Application.routes.draw do

  resources :setting_mains, except: :index


  resources :brands


  resources :areas

  resources :purchase_orders do
    member do
      put :canceled
    end
    collection do
      get :quotation_list
    end
  end

  get "site/index"

  resources :quotations do
    resource :purchase_orders
    member do
      get :fill_costs
      put :save_fill_costs
      get :toggle
      get :status_change
    end
    collection do
      get :compare
      get :pending_requeriment
    end
  end

  resources :providers

  resources :movement_items, only: [:update, :index]

  resources :movements, only: [:index, :show, :destroy] do
    member do
      get :print
    end
    collection do
      get :new_get_out_purchase_order
      get :new_purchase
      get :purchase_orders
      get :pending_incoming_purchases
      post :create_get_out_purchase_order
      post :create_purchase
      get :new_incoming
      post :create_incoming
      # get :new_get_out
      post :create_get_out
      get :pending_input_notes
    end
  end

  resources :requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :serv_requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :products
  resources :groups
  resources :sub_groups
  resources :categories
  resources :brands
  resources :input_notes

  resources :ware_houses do
    get 'new_get_out' => 'movements#new_get_out'
    get 'initial' => 'movements#initial'
    get 'physical' => 'product_ware_houses#index'
    collection do
      get :own
      get :kardex
    end
  end

  resources :product_ware_houses, only: [:index, :update] do
    collection do
      put :update_multiple
    end
  end

  devise_for :users

  resources :users

  root :to => 'site#index'

  get 'dynamic_groups_by_type' => 'javascripts#dynamic_groups_by_type'
  get 'product_by_ware_house' => 'javascripts#product_by_ware_house'
  get 'products_by_ware_house' => 'javascripts#products_by_ware_house'
  get 'dynamic_sub_groups' => 'javascripts#dynamic_sub_groups'
  get 'dynamic_categories' => 'javascripts#dynamic_categories'
  get 'dynamic_products' => 'javascripts#dynamic_products'
  get 'dynamic_brands_by_group' => 'javascripts#dynamic_brands_by_group'
  get 'dynamic_brands_by_sub_group' => 'javascripts#dynamic_brands_by_sub_group'

  get 'load_other_products_from_category' => 'javascripts#load_other_products_from_category'
  get 'load_other_categories_from_sub_group' => 'javascripts#load_other_categories_from_sub_group'
  get 'load_other_sub_groups_from_group' => 'javascripts#load_other_sub_groups_from_group'
  get 'load_other_brands_from_sub_group' => 'javascripts#load_other_brands_from_sub_group'

  get 'get_product' => 'javascripts#get_product'

end

app/models/requeriment.rb
class Requeriment < ActiveRecord::Base
  NORMAL    = 1
  PENDING   = 2
  PROCESS   = 3
  VALUED    = 4
  PARTIAL   = 5
  COMPLETED = 6
  CANCELED  = 7

  GOODS     = 1
  SERVICES  = 2

  STATUSES = {
    NORMAL    => 'borrador',
    PENDING   => 'pendiente',
    PROCESS   => 'cotizando',
    VALUED    => 'cotizado',
    PARTIAL   => 'cotizado parcial',
    COMPLETED => 'atendido',
    CANCELED  => 'anulado'
  }

  TYPE = {
    GOODS => 'Requerimiento de bienes',
    SERVICES => 'Requerimiento de servicios'
  }

  TYPE_ORDER = {
    GOODS => 'Orden de Compra',
    SERVICES => 'Orden de Servicio'
  }


  belongs_to :ware_house
  belongs_to :area
  belongs_to :responsible, class_name: 'User'
  has_many :requeriment_items, dependent: :destroy, inverse_of: :requeriment
  has_many :quotations, dependent: :destroy, inverse_of: :requeriment

  attr_accessible :reference, :description , :requeriment_items_attributes, :responsible_id, :ware_house_id,
                  :status_text, :deadline, :area_id, :status, :observation, :nam, :type_requeriment

  accepts_nested_attributes_for :requeriment_items, allow_destroy: true

  scope :completes, ->(){where(completed: true)}
  validates :deadline, :area_id,
            :responsible_id, presence: true

  validates_inclusion_of :status, :in => STATUSES.keys
  after_create :generate_name

  def type_text
    TYPE[self.type_requeriment]
  end

  def status_text
    STATUSES[self.status]
  end

  def status_text_order
    TYPE_ORDER[self.type_requeriment]
  end

  private

  def generate_name
    new_name = Requeriment.maximum(:name) || '00000000'
    self.update_column(:name, new_name.next)
  end

  def change_status
    if self.status != nil
      if self.status == NORMAL
        self.update_column(:status, PENDING)
      end
    end
  end
end

app/controllers/requeriments_controller.rb
class RequerimentsController < ApplicationController
  load_and_authorize_resource

  def index
    @search = @requeriments.order('id desc').search(params[:search])
    @requeriments = @search.page(params[:page])
    @req = Requeriment.all
    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json{
        render json: @requeriment, include:  :requeriment_items
      }
      format.pdf{
        render pdf: "requerimiento_#{@requeriment.name}", wkhtmltopdf: '/usr/bin/wkhtmltopdf', page_size: 'A4', margin: {top: 0, bottom: 0, left: 0, right: 0}, lowquality: false
        # render pdf: "requerimiento_#{@requeriment.name}", wkhtmltopdf: '/usr/local/bin/wkhtmltopdf', page_size: 'A4', margin: {top: 0, bottom: 0, left: 0, right: 0}, lowquality: false
      }
    end
  end

  def new
    @requeriment.type_requeriment = Requeriment::GOODS
    # @requeriment.requeriment_items.build
    @groups = Group.where("type_group = ?", 1)#bienes por defecto
    respond_to do |format|
      format.html
    end
  end

  def edit
    @requeriment.requeriment_items
    @groups =  if @requeriment.type_requeriment == Requeriment::GOODS
      Group.where("type_group = ?", 1)#bienes por defecto
    else
      Group.where("type_group = ?", 2)
    end
  end

  def create
    if current_user.responsible_ware_house?
      @requeriment.ware_house_id = current_user.ware_house.id
      @requeriment.type_requeriment = Requeriment::GOODS
    end

    @requeriment.status = 1
    @requeriment.responsible_id = current_user.id

    respond_to do |format|
      if @requeriment.save
        format.html { redirect_to @requeriment, notice: t(:data_created) }
      else
        @groups = Group.where("type_group = ?", @requeriment.type_requeriment)
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @requeriment.update_attributes(params[:requeriment])
        format.html { redirect_to requeriment_path, notice: t(:data_updated) }
      else
        @groups = Group.where("type_group = ?", 1)#bienes por defecto
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    if Quotation.find_by_requeriment_id(@requeriment.id)

    else
      @requeriment.destroy
    end

    respond_to do |format|
      format.html { redirect_to requeriments_url }
    end
  end

  def toggle
    @requeriment.toggle! :completed
    respond_to do |format|
      format.html { redirect_to requeriments_url }
    end
  end

  def status_change
    if @requeriment.status == Requeriment::NORMAL
      @requeriment.update_column(:status, Requeriment::PENDING)

      respond_to do |format|
        format.html { redirect_to requeriments_url }
      end
    elsif @requeriment.status == Requeriment::PENDING
      @requeriment.update_column(:status, Requeriment::PROCESS)

      respond_to do |format|
        format.html { redirect_to quotations_url }
      end
    end
  end
end

app/views/requeriments/_form.html.erb
<%= simple_nested_form_for(@requeriment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row-fluid"><div class="span6"><%= f.input :reference, label: "Nro. de referencia" %></div></div>
    <div class="row-fluid"><div class="span12"><%= f.input :deadline, as: :datepicker %></div></div>
    <div class="row-fluid"><div class="span8"><%= f.input :description, label: 'Titulo:', input_html: {class: 'span8'} %></div></div>

    <div class="row-fluid"><div class="span12">
      <% if current_user.super_admin? %>
        <%= f.association :area, input_html: {class: 'span12'} %>
      <% else %>
        <%= f.association :area, selected: current_user.area.id, input_html: {class: 'span12'} %>
      <% end %>
    </div></div>

    <% if current_user.administrator? || current_user.super_admin? %>
      <%= f.input :type_requeriment, collection: [["Bienes", 1], ["Servicios", 2]], as: :radio_buttons, default: 1, input_html: {class: 'requeriment_type'} %>
      <div class="row-fluid"><div class="span8"><%= f.association :ware_house, collection: current_user.filter_ware_houses, include_blank: "- seleccione almacen -", label_method: :name, input_html: {class: 'span8'} %></div></div>
    <% end %>

    <table class="table table-striped table-hover table-condensed table-nested">
      <thead>
        <tr>
          <th></th>
          <th>Grupo</th>
          <th>SubGrupo</th>
          <th>Categoria</th>
          <th>Producto</th>
          <th>Marca</th>
          <th>Cantidad</th>
          <th>Modelo</th>
          <th>Detalle</th>
        </tr>
      </thead>
      <tbody id="requeriment_items">
        <%= f.fields_for :requeriment_items, wrapper: false %>
      </tbody>
      <tfoot>
        <td colspan='4'><%= f.link_to_add '<i class="icon-plus"></i> Agregar'.html_safe, :requeriment_items, :data => { :target => "#requeriment_items" } %></td>
      </tfoot>
    </table>
  </div>

  <div class="row-fluid"><div class="span12"><%= f.input :observation, input_html: {class: 'span12', rows: '5'}, label: 'Nota:' %></div></div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/requeriments/_requeriment.html.erb
<div class="row-fluid">
  <div class="span12">
    <p class="text-center font-header"><strong>Requerimiento Nro. <%=@requeriment.name%></strong></p>

    <div class="span12">
      <div class="span4"><strong>Titulo:</strong></div>
      <div class="span8"><%= @requeriment.description %></div>
    </div>

    <% if @requeriment.area %>
      <div class="span12">
        <div class="span4"><strong>Área solicitante:</strong></div>
        <div class="span8"><%= @requeriment.area.name %></div>
      </div>
    <% end %>

    <% if @requeriment.ware_house %>
      <div class="span12">
        <div class="span4"><strong>Almacen:</strong></div>
        <div class="span8"><%= @requeriment.ware_house.name %></div>
      </div>
    <% end %>

    <div class="span12">
      <div class="span4"><strong>Solicitante:</strong></div>
      <div class="span8"><%= @requeriment.responsible.name %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Nro. Referencia:</strong></div>
      <div class="span8"><%= @requeriment.reference %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Fecha solicitud:</strong></div>
      <div class="span8"><%= l(@requeriment.created_at) %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Fecha limite de entrega:</strong></div>
      <div class="span8"><%=  l(@requeriment.deadline) %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Nota:</strong></div>
      <div class="span8"><%= @requeriment.observation %></div>
    </div>

    <table class="table table-striped table-condensed table_summary">
      <thead>
        <tr>
          <th>Producto</th>
          <th>Cantidad</th>
          <th>Unidad</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Detalle</th>
        </tr>
      </thead>
      <tbody>
        <% @requeriment.requeriment_items.each do |item| %>
          <tr>
            <td><%=item.product.description %></td>
            <td><%=item.quantity%></td>
            <td><%=item.product.measurement_unit_name %></td>
            <td><%=item.brand.try(:description) %></td>
            <td><%=item.model %></td>
            <td><%=item.detail %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/requeriments/_requeriment_item_fields.html.erb
<tr class='row_item fields'>
  <td><%= f.link_to_remove '<i class="icon-minus"></i>'.html_safe %></td>
  <td>
    <%= f.input :group_id, collection: @groups.map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_group'}, prompt: '- Seleccione una opcion -' %>
  </td>
  <td>
    <%= f.input :sub_group_id, collection: SubGroup.by_group(f.object.group_id).map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_sub_group'} %>
  </td>
  <td>
    <%= f.input :category_id, collection: Category.by_sub_group(f.object.sub_group_id).map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_category'} %>
  </td>
  <td>
    <%= f.association :product, collection: Product.by_category(f.object.category_id).map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_product'} %>
  </td>
  <td>
    <%= f.association :brand, collection: Brand.all.map{|m| [m.description, m.id]}, label: false, input_html: {class: 'filter_brand'}, prompt: ' - seleccione una opcion -' %>
  </td>
  <td><%= f.input :quantity, label: false, wrapper: false %></td>
  <td><%= f.input :model, label: false, wrapper: false %></td>
  <td><%= f.input :detail, label: false, wrapper: false, input_html: {cols: 10, rows: 2} %></td>
</tr>

app/views/requeriments/_requeriment_pdf.html.erb
<div class="row-fluid">
  <div class="span12">
    <p class="text-center font-header"><strong>REQUISICION Nro. <%=@requeriment.name%></strong></p>

    <table class="table_summary table">
      <tr>
        <td><strong>Referencia:</strong></td>
        <td><%= @requeriment.description %></td>
        <td><strong>Nro. Referencia:</strong></td>
        <td><%= @requeriment.reference %></td>
      </tr>

      <tr>
        <td><strong>Fecha de solicitud:</strong></td>
        <td><%= l(@requeriment.created_at) %></td>
        <td><strong>Fecha limite de entrega:</strong></td>
        <td><%= l(@requeriment.deadline) %></td>
      </tr>

      <tr>
        <td><strong>Area que solicita:</strong></td>
        <td><%= @requeriment.area.name %></td>
        <td><strong>Solicitante:</strong></td>
        <td><%= @requeriment.responsible.name %></td>
      </tr>

      <tr>
        <td><strong>Tipo de Requisicion:</strong></td>
        <td><%= @requeriment.type_text %></td>
        <td><strong>Almacen:</strong></td>
        <td><%= @requeriment.ware_house.name %></td>
      </tr>

      <tr>
        <td><strong>Nota:</strong></td>
        <td><%= @requeriment.observation %></td>
      </tr>
    </table>

    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Producto</th>
          <th>Cantidad</th>
          <th>Unidad</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Detalle</th>
        </tr>
      </thead>
      <tbody>
        <% @requeriment.requeriment_items.each do |item| %>
          <tr>
            <td><%=item.product.description %></td>
            <td><%=item.quantity%></td>
            <td><%=item.product.measurement_unit_name %></td>
            <td><%=item.brand.try(:description) %></td>
            <td><%=item.model %></td>
            <td><%=item.detail %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<footer>
  <hr>
  <p>Solicitanteee: <%= @requeriment.responsible.name %></p>
</footer>

app/views/requeriments/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Acciones</li>
      <%=nav_link('Requerimientos', requeriments_path)%>
      <%=nav_link('Nuevo', new_requeriment_path) if can? :create, Requeriment%>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/requeriments/edit.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3>Actualizar requerimiento</h3>
  <%= render 'form', edit: true  %>
</div>
<script>
  var requeriment_edit = true;
</script>

app/views/requeriments/index.html.erb
<%=render 'sidebar'%>
<div class="span9">
  <h3 class='text-center'>Requerimientos</h3>

  <%= simple_form_for(@search, html: {class: 'form-search' }) do |f|%>
    <%= f.label :name_contains, "Nombre: " %>
    <%= f.text_field :name_contains, class: 'search-query'%>
    <button type="submit" class="btn">Buscar</button>
  <% end %>

  <table class="table table-striped table-hover table-condensed">
    <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo de requerimiento</th>
      <th>Almacén</th>
      <th>Estado</th>
      <th>Ver</th>
      <th>Editar</th>
      <th>Borrar</th>
    </tr>
    </thead>
    <tbody>

    <% @requeriments.each do |requeriment| %>
      <% if (requeriment.area.id == current_user.area_id) || current_user.super_admin? %>
        <tr>
          <td><%= requeriment.name %></td>
          <td><%= requeriment.type_text %></td>

          <% if current_user.administrator? || current_user.super_admin? %>
            <% if requeriment.ware_house %>
              <td><%= requeriment.ware_house.name %></td>
            <% else %>
              <% if requeriment.type_requeriment == Requeriment::GOODS %>
                <%=simple_form_for(@req,:url => "/requeriments/#{requeriment.id}", html: {class: 'form-search' }) do |f|%>
                    <td><%= f.collection_select(:ware_house_id , WareHouse.all, :id, :name, prompt: true) %>
                      <button type="submit" class="btn">Asignar</button>
                    </td>
                <% end %>
                <% else %>
                  <td></td>
                <% end %>
            <% end %>
            <% if requeriment.status == Requeriment::NORMAL %>
              <td><%= link_to_if(can?(:change, requeriment), requeriment.status_text.to_s, status_change_requeriment_path(requeriment))%></td>
            <% else %>
              <th><%= requeriment.status_text %></th>
            <% end %>
          <% else %>
            <% if requeriment.ware_house %>
                <td><%= requeriment.ware_house.name %></td>
            <% else %>
                <td>No asignado</td>
            <% end %>
            <th><%= requeriment.status_text %></th>
          <% end %>

          <td><%= show_link requeriment %></td>
          <% if requeriment.status == Requeriment::NORMAL %>
            <td><%= edit_link(edit_requeriment_path(requeriment)) if can? :edit, requeriment %></td>
            <td><%= destroy_link requeriment%></td>
          <% else %>
              <% if current_user.administrator? || current_user.super_admin? %>
                  <td><%= edit_link(edit_requeriment_path(requeriment)) if can? :edit, requeriment %></td>
                  <td><%= destroy_link requeriment%></td>
              <% else %>
                  <td></td>
                  <td></td>
              <% end %>
          <% end %>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>

  <%= paginate @requeriments %>

</div>

app/views/requeriments/new.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3 class='text-center'>Nuevo requerimiento</h3>
	<%= render 'form' %>
</div>

app/views/requeriments/show.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<p id="notice"><%= notice %></p>

	<%= render @requeriment %>
  <% if @requeriment.status == Requeriment::NORMAL %>
	 <%= edit_button(edit_requeriment_path(@requeriment)) if can? :edit, @requeriment %>
	 <%= destroy_button @requeriment %>
  <% elsif current_user.administrator? || current_user.super_admin? %>
    <%= edit_button(edit_requeriment_path(@requeriment)) if can? :edit, @requeriment %>
    <%= destroy_button @requeriment %>
  <% end %>
	<%= print_button @requeriment %>
</div>

app/views/requeriments/show.pdf.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= wicked_pdf_stylesheet_link_tag 'pdf'%>
     <style>
      	body *{margin:0px;padding:0px;}
    </style>

  </head>
  <body>
    <%= wicked_pdf_image_tag('logosa.jpg')%>
    <div class="header_right"><%= l Time.now %></div>
    <br/><br/>
    <%= render 'requeriments/requeriment_pdf.html.erb'%>
  </body>
</html>