config/routes.rb
Logistic::Application.routes.draw do

  resources :setting_mains, except: :index


  resources :brands


  resources :areas

  resources :purchase_orders do
    member do
      put :canceled
    end
    collection do
      get :quotation_list
    end
  end

  get "site/index"

  resources :quotations do
    resource :purchase_orders
    member do
      get :fill_costs
      put :save_fill_costs
      get :toggle
      get :status_change
    end
    collection do
      get :compare
      get :pending_requeriment
    end
  end

  resources :providers

  resources :movement_items, only: [:update, :index]

  resources :movements, only: [:index, :show, :destroy] do
    member do
      get :print
    end
    collection do
      get :new_get_out_purchase_order
      get :new_purchase
      get :purchase_orders
      get :pending_incoming_purchases
      post :create_get_out_purchase_order
      post :create_purchase
      get :new_incoming
      post :create_incoming
      # get :new_get_out
      post :create_get_out
      get :pending_input_notes
    end
  end

  resources :requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :serv_requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :products
  resources :groups
  resources :sub_groups
  resources :categories
  resources :brands
  resources :input_notes

  resources :ware_houses do
    get 'new_get_out' => 'movements#new_get_out'
    get 'initial' => 'movements#initial'
    get 'physical' => 'product_ware_houses#index'
    collection do
      get :own
      get :kardex
    end
  end

  resources :product_ware_houses, only: [:index, :update] do
    collection do
      put :update_multiple
    end
  end

  devise_for :users

  resources :users

  root :to => 'site#index'

  get 'dynamic_groups_by_type' => 'javascripts#dynamic_groups_by_type'
  get 'product_by_ware_house' => 'javascripts#product_by_ware_house'
  get 'products_by_ware_house' => 'javascripts#products_by_ware_house'
  get 'dynamic_sub_groups' => 'javascripts#dynamic_sub_groups'
  get 'dynamic_categories' => 'javascripts#dynamic_categories'
  get 'dynamic_products' => 'javascripts#dynamic_products'
  get 'dynamic_brands_by_group' => 'javascripts#dynamic_brands_by_group'
  get 'dynamic_brands_by_sub_group' => 'javascripts#dynamic_brands_by_sub_group'

  get 'load_other_products_from_category' => 'javascripts#load_other_products_from_category'
  get 'load_other_categories_from_sub_group' => 'javascripts#load_other_categories_from_sub_group'
  get 'load_other_sub_groups_from_group' => 'javascripts#load_other_sub_groups_from_group'
  get 'load_other_brands_from_sub_group' => 'javascripts#load_other_brands_from_sub_group'

  get 'get_product' => 'javascripts#get_product'

end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  NORMAL    = 1
  SENT      = 2
  CLOCKED   = 3
  GENERATE  = 4
  COMPLETED  = 5
  CANCELED  = 6

  STATUSES = {
      NORMAL    => 'borrador',
      SENT      => 'enviado',
      CLOCKED   => 'cerrado',
      GENERATE  => 'OC generada',
      COMPLETED  => 'Completada',
      CANCELED  => 'OC Anulado'
  }

  belongs_to :provider
  belongs_to :requeriment
  has_many :quotation_items, dependent: :destroy, inverse_of: :quotation
  accepts_nested_attributes_for :quotation_items, allow_destroy: true
  attr_accessible :provider_id, :completed, :quotation_items_attributes, :observations, :validity, :delivery, :pay_form, :requeriment_id, :winner
  scope :completes, ->(){where(winner: true)}
  validates :provider_id, presence: true
  validates_inclusion_of :status, :in => STATUSES.keys
  after_create :generate_name
  after_update :change_status

  def status_text
    STATUSES[self.status]
  end

  private

  def generate_name
    new_name = Quotation.maximum(:name) || '00000000'
    self.update_column(:name, new_name.next)
  end

  private
  def change_status
    if status == NORMAL
      self.update_column(:status, SENT)
    end
  end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  load_and_authorize_resource

  def index
    @search = @quotations.order('id desc').search(params[:search])
    @quotations = @search.page(params[:page]).per(15)
    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json{
        render json: @quotation, include:  :quotation_items
      }
      format.pdf{
        render pdf: "cotizacion_#{@quotation.name}", wkhtmltopdf: '/usr/bin/wkhtmltopdf', page_size: 'A4', margin: {top: 0, bottom: 0, left: 0, right: 0}, lowquality: false
      }
    end
  end

  def new
    @requeriment_id = params[:requeriment_id]
    @requeriment = Requeriment.find (params[:requeriment_id])
    product_list = RequerimentItem.select("product_id, brand_id, model, detail, sum(quantity) as sum").group(:product_id, :brand_id, :model, :detail).joins(:requeriment).where(requeriments: {id: @requeriment_id, completed: false, status: 2})
      product_list.each do |product_requeriment|
      @quotation.quotation_items.build(product_id: product_requeriment.product_id, model: product_requeriment.model, detail: product_requeriment.detail, brand_id: product_requeriment.brand_id, quantity: product_requeriment.sum)
    end

    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  def create
    @quotation.status = Quotation::SENT
    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Cotizacion fue creado correctamente.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @quotation.update_attributes(params[:quotation])
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    if PurchaseOrder.find_by_quotation_id(@quotation.id)

    else
      @quotation.destroy
    end

    respond_to do |format|
      format.html { redirect_to quotations_url }
    end
  end

  def fill_costs

    respond_to do |format|
      format.html
    end
  end

  def save_fill_costs
    if @quotation.status == Quotation::SENT
      @quotation.status = Quotation::CLOCKED
    end

    respond_to do |format|
      if @quotation.update_attributes(params[:quotation])
        format.html { redirect_to @quotation, notice: 'Cotizacion fue actualizado correctamente.' }
      else
        format.html { render action: "fill_costs" }
      end
    end
  end

  def toggle
    @quotation.toggle! :completed
    respond_to do |format|
      format.html { redirect_to quotations_url }
    end
  end

  def compare
    #@quotations = @quotations.select("requeriment_id, count(id) as count").group(:requeriment_id).where(:status => Requeriment::PROCESS)
    all_requeriments = Requeriment.where(:status => Requeriment::PROCESS, :area_id => @current_user.area_id).order('id desc')
    @requeriments = []
    all_requeriments.each do |requeriment|
      @requeriments.append({
                               'id' => requeriment.id,
                               'area_id' => requeriment.area.id,
                               'name' => requeriment.name,
                               'all_quotations' => Quotation.where(:requeriment_id => requeriment.id).count(:id),
                               'closed_quotations' => Quotation.where(:requeriment_id => requeriment.id, :status => 3).count(:id),
                               'model' => requeriment,
                           })
    end


    if params[:compare_requeriment_id].present?
      @active = true
      for requeriment_item in RequerimentItem.where(:requeriment_id => params[:compare_requeriment_id]) do
        if params[:"quotation_details_#{requeriment_item.product.id.to_s}_id"].present?
          @quotation_item = QuotationItem.update(params[:"quotation_details_#{requeriment_item.product.id.to_s}_id"], :winner => true)
          Quotation.update(@quotation_item.quotation_id, :winner => true)
        elsif
          @active = false
        end
      end

      if @active
        Requeriment.update(params[:compare_requeriment_id], :status => Requeriment::VALUED)
      else
        Requeriment.update(params[:compare_requeriment_id], :status => Requeriment::PARTIAL)
      end

      respond_to do |format|
        format.html { redirect_to quotations_url }
      end

    elsif params[:requeriment_id].present?
      @requeriment = Requeriment.find params[:requeriment_id]
      @quotations_compare = @requeriment.quotations.includes(:provider, :quotation_items => :product).where(status: Requeriment::PROCESS)
      @products = @quotations_compare.map(&:quotation_items).flatten.map(&:product).flatten.uniq
      respond_to do |format|
        format.html
      end
    end

  end

  def pending_requeriment
    all_requeriments = Requeriment.where(:status => Requeriment::PENDING)
    @requeriments = []
    all_requeriments.each do |requeriment|

      @requeriments.append({
                               'id' => requeriment.id,
                               'area_id' => requeriment.area.id,
                               'name' => requeriment.name,
                               'all_quotations' => Quotation.where(:requeriment_id => requeriment.id).count(:id),
                               'closed_quotations' => Quotation.where(:requeriment_id => requeriment.id, :status => 3).count(:id),
                           })
    end
    #requeriments.each do |requeriment|
    #  @quotation.quotation_items.build(product_id: requeriment.id, quantity: requeriments.name)
    #end
    respond_to do |format|
      format.html
    end
  end
end

app/views/quotations/_compares.html.erb
<div class="row-fluid">
  <div class="span12">
    <p><strong>CUADRO COMPARTIVO</strong></p>
    <ul>
      <li><strong>Nro. Requerimiento: </strong><%= link_to @requeriment.name, @requeriment %></li>
      <li><strong>Titulo Requerimiento: </strong><%= @requeriment.description %></li>
    </ul>

    <%= form_tag compare_quotations_path, method: :get do %>
      <table class="table table-condensed table-background">
        <thead>
          <tr>
            <th colspan="8">Producto</th>
          </tr>
          <tr>
            <th>Proveedor</th>
            <th>Cotizacion</th>
            <th>Fecha cotizacion</th>
            <th>Cantidad</th>
            <th>Precio Unit.</th>
            <th>Precio Total</th>
            <th>Ganador</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr class="success">
              <td colspan="8"><strong><%= "#{product.description} - #{product.name}" %></strong></td>
            </tr>
            <% @quotations_compare.map(&:quotation_items).flatten.select{|i| i.product_id == product.id}.each do |quotation_item|%>
              <tr>
                <td><%= quotation_item.quotation.provider.name%></td>
                <td><%= link_to(quotation_item.quotation.name, quotation_path(quotation_item.quotation))%></td>
                <td><%=l(quotation_item.quotation.created_at)%></td>
                <td><%= quotation_item.quantity%></td>
                <td><%= number_to_currency(quotation_item.cost_unit) %></td>
                <td><%= number_to_currency(quotation_item.cost_total) %></td>
                <td><%= radio_button_tag ("quotation_details_"+quotation_item.product.id.to_s+"_id"), quotation_item.id  %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <%= hidden_field_tag "compare_requeriment_id", params[:requeriment_id] %>
      <%= submit_tag 'Enviar' %>
    <%end%>
  </div>
</div>

app/views/quotations/_form.html.erb
<%= simple_form_for(@quotation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :provider, input_html: {class: 'my_select2 span6'} %>
    <table class="table table-striped table-hover table-condensed table-nested">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Unidad</th>
        <th>Modelo</th>
        <th>Marca</th>
        <th>Detalle</th>
        <th>¿Quitar?</th>
      </tr>
    </thead>
    <tbody>
      <%= f.simple_fields_for :quotation_items do |quotation_item_form| %>
        <%= render 'quotation_item_fields', f: quotation_item_form %>
      <% end %>
    </tbody>
  </table>
  <%= f.input :observations, input_html: {class: 'span12', rows: 5}%>
    <% if @requeriment_id %>
        <%= f.input :requeriment_id, :as => :hidden, :input_html => { :value => @requeriment_id }%>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quotations/_form_fill_costs.html.erb
<%= simple_form_for(@quotation, url: save_fill_costs_quotation_url(@quotation)) do |f| %>
  <%= f.error_notification %>

  <div class="span12">
    <div class="span4"><strong>Nro. Cotizacion:</strong></div>
    <div class="span8"><%= link_to @quotation.name, @quotation %></div>
  </div>

  <div class="span12">
    <div class="span4"><strong>Proveedor:</strong></div>
    <div class="span8"><%= @quotation.provider.name %></div>
  </div>

  <div class="span12">
    <div class="span4"><strong>Proveedor RUC:</strong></div>
    <div class="span8"><%= @quotation.provider.ruc %></div>
  </div>

  <div class="span12">
    <div class="span4"><strong>Fecha creacion de cotizacion:</strong></div>
    <div class="span8"><%= @quotation.created_at %></div>
  </div>

  <div class="form-inputs">

    <%=f.input :validity%>
    <%=f.input :delivery%>
    <%=f.input :pay_form%>

    <table class="table table-striped table-hover table-condensed table-nested">
      <thead>
        <tr>
          <th>Producto</th>
          <th>Cantidad</th>
          <th>Precio Unit.</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Detalle</th>
        </tr>
      </thead>
      <tbody>
        <%=f.simple_fields_for :quotation_items do |quotation_item_form|%>
          <%= render 'quotation_item_fill_costs_fields', f: quotation_item_form %>
        <%end%>
      </tbody>
    </table>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quotations/_quotation.html.erb
<div class="row-fluid">
  <div class="span12">
    <h3 class="text-center font-header">SOLICITUD DE COTIZACION Nro. <%= @quotation.name%></h3>

    <div class="span12">
      <div class="span4"><strong>Nro. Requerimiento:</strong></div>
      <div class="span7"><%= link_to @quotation.requeriment.name, @quotation.requeriment %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Proveedor:</strong></div>
      <div class="span7"><%= @quotation.provider.name %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Contacto:</strong></div>
      <div class="span7"><%= @quotation.provider.resposible %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Ruc:</strong></div>
      <div class="span7"><%= @quotation.provider.ruc %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Direccion:</strong></div>
      <div class="span7"><%= @quotation.provider.address %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Telefono:</strong></div>
      <div class="span7"><%= @quotation.provider.phone %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Fecha creacion cotizacion:</strong></div>
      <div class="span7"><%= l(@quotation.created_at) %></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Fecha estimada de entrega:</strong></div>
      <div class="span7"><%= l @quotation.requeriment.deadline %></div>
    </div>

    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Producto</th>
          <th>Cantidad</th>
          <th>Unidad</th>
          <th>Precio Unitario</th>
          <th>Total</th>
          <th>Modelo</th>
          <th>Marca</th>
          <th>Detalle</th>
        </tr>
      </thead>
      <tbody>
        <% @quotation.quotation_items.each do |item| %>
          <tr>
            <td><%= item.product.description%></td>
            <td><%= item.quantity%></td>
            <td><%= item.product.measurement_unit_name %></td>
            <td><%= number_to_currency(item.cost_unit) %></td>
            <td><%= number_to_currency(item.cost_total) %></td>
            <td><%= item.model %></td>
            <td><%= item.brand.try(:description) %></td>
            <td><%= item.detail %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="span12">
      <div class="span4"><strong>Validez:</strong></div>
      <div class="span7"><%= @quotation.validity%></div>
    </div>
    <div class="span12">
      <div class="span4"><strong>Entrega:</strong></div>
      <div class="span7"><%=@quotation.delivery%></div>
    </div>
    <div class="span12">
      <div class="span4"><strong>Forma de pago:</strong></div>
      <div class="span7"><%=@quotation.pay_form%></div>
    </div>

    <div class="span12">
      <div class="span4"><strong>Observaciones:</strong></div>
      <div class="span7"><%= simple_format @quotation.observations%></div>
    </div>
  </div>
</div>

app/views/quotations/_quotation_item_fields.html.erb
<tr>
  <td><%= f.object.product.description %><%=f.input :product_id, as: :hidden %></td>
  <td class: 'span5'><%= f.input :quantity, label: false, wrapper: false, input_html: {class: 'span9'} %></td>
  <td><%= f.object.product.measurement_unit_name %></td>
  <td><%= f.object.model %> <%=f.input :model, as: :hidden %></td>
  <td><%= f.object.brand.try(:description) %><%=f.input :brand_id, as: :hidden %></td>
  <td><%= f.object.detail %><%=f.input :detail, as: :hidden %></td>
  <td><%= f.check_box :_destroy %></td>
</tr>

app/views/quotations/_quotation_item_fill_costs_fields.html.erb
<tr>
	<td><%= f.object.product.description %><%=f.input :product_id, as: :hidden%></td>
	<td><%= f.object.quantity%></td>
	<td><%= f.input :cost_unit, label: false, wrapper: false, input_html: {class: 'span10'}%></td>
  <td><%= f.object.brand.try(:description) %></td>
  <td><%= f.object.model %></td>
  <td><%= f.object.detail %></td>
</tr>

app/views/quotations/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Acciones</li>
      <%=nav_link('Solicitud de Cotizaciones', pending_requeriment_quotations_path)%>
      <%=nav_link('Cotizaciones', quotations_path)%>
      <%=nav_link('Cuadro comparativo', compare_quotations_path)%>
      <%=nav_link('Cotizaciones Ganadoras', quotation_list_purchase_orders_path)%>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/quotations/compare.html.erb
<%= render 'sidebar' %>
<div class="span9">
  <h3 class='text-center'>Comparar</h3>

  <%= form_tag compare_quotations_path, method: :get do %>
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th></th>
          <th>Nro. Requerimiento</th>
          <th>Cantidad de Cotizaciones</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @requeriments.each do |requeriment| %>
          <% if requeriment['area_id'] == current_user.area_id || current_user.super_admin? %>
            <tr>
              <td><%= radio_button_tag "requeriment_id", requeriment['id']%></td>
              <td><%= requeriment['name'] %></td>
              <td><%= requeriment['all_quotations'] %></td>
              <td><%= show_link requeriment['model']  %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= submit_tag 'comparar' %>
  <% end %>
</div>

<%= render 'compares' if @products.present? %>

app/views/quotations/edit.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3 class='text-center'>Actualizar cotizacion</h3>
	<%= render 'form' %>
</div>

app/views/quotations/fill_costs.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3 class='text-center'>Llenar precios</h3>
	<%= render 'form_fill_costs' %>
</div>

app/views/quotations/index.html.erb
<%=render 'sidebar'%>
<div class="span9">
  <h3 class='text-center'>Cotizaciones</h3>
  <%= simple_form_for(@search, html: {class: 'form-search' }) do |f| %>
    <%= f.label :name_or_provider_name_contains, "Numero o Proveedor: " %>
    <%= f.text_field :name_or_provider_name_contains, class: 'search-query'%>
    <button type="submit" class="btn">Buscar</button>
  <% end %>

  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Cotización</th>
        <th>Requerimiento</th>
        <th>Tipo de Requerimiento</th>
        <th>Proveedor</th>
        <th>Estado</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @quotations.each do |quotation| %>
        <% if quotation.requeriment.try(:area).try(:id) == current_user.area_id || current_user.role_id == 1 %>
          <tr>
            <td><%= quotation.name %></td>
            <td><%= link_to quotation.requeriment.name, requeriment_path(quotation.requeriment.id) %></td>
            <td><%= quotation.requeriment.type_text %></td>
            <td><%= quotation.provider.name %></td>
            <th><%= quotation.status_text.to_s %></th>
            <td><%= show_link quotation %></td>
            <td><%= edit_link edit_requeriment_quotation_path(quotation.requeriment.id, quotation) if (quotation.status == Quotation::NORMAL || quotation.status == Quotation::SENT) %></td>
            <td><%= destroy_link quotation%></td>
            <% if quotation.status == Quotation::SENT %>
              <td><%= link_to 'Llenar precios', fill_costs_quotation_path(quotation) %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @quotations%>
</div>

app/views/quotations/pending_requeriment.html.erb
<%=render 'sidebar'%>
<div class="span9">
  <h3 class='text-center'>Requerimientos Pendientes</h3>
  <table class="table table-striped table-hover table-condensed table-nested">
    <thead>
    <tr>
      <th>Nro requerimiento</th>
      <th>Cantidad de Cotizaciones</th>
      <th>Cotizaciones recibidas</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @requeriments.each do |requeriment| %>
        <% if requeriment['area_id'] == current_user.area_id || current_user.role_id == 1 %>
            <tr>
              <td><%= requeriment['name'] %></td>
              <th><%= requeriment['all_quotations'] %> </th>
              <th><%= requeriment['closed_quotations'] %></th>
              <td><%= link_to 'cotizar', new_requeriment_quotation_path(requeriment['id']) %> / <%= link_to  'Cerrar', status_change_requeriment_path(requeriment)%></td>
            </tr>
        <% end %>
    <% end %>
    </tbody>

  </table>
</div>

app/views/quotations/show.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<p id="notice"><%= notice %></p>

	<%=render @quotation%>

	<%= edit_button edit_quotation_path(@quotation) if (@quotation.status == Quotation::NORMAL || @quotation.status == Quotation::SENT) %>
	<%= destroy_button @quotation %>
	<%= print_button @quotation %>
</div>

app/views/quotations/show.pdf.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= wicked_pdf_stylesheet_link_tag 'pdf'%>
     <style>
      	body *{margin:0px;padding:0px;}
    </style>

  </head>
  <body>
    <%= wicked_pdf_image_tag('logosa.jpg')%>
    <br/><br/>
    <div class="row-fluid">
      <div class="span12">
        <p class="text-center font-header"><strong>COTIZACION Nro. <%=@quotation.name%></strong></p>
        <br/>
        <br/>
        <%= @quotation.created_at %>
        <br/>
        <br/>
        <p>Señores:</p>
        <p><strong><%= @quotation.provider.name %></strong></p>
        <br/><br/>
        Por medio de la presente...<br/><br/>

        <table class="table table-condensed table-bordered">
          <thead>
            <tr>
              <th>Item</th>
              <th>Producto</th>
              <th>Cantidad</th>
            </tr>
          </thead>
          <tbody>
            <%@quotation.quotation_items.each_with_index do |item, i|%>
              <tr>
                <td><%=i + 1%></td>
                <td><%=item.product.name%></td>
                <td><%=item.quantity%></td>
              </tr>
            <%end%>
          </tbody>
        </table>
        <div class="span12">
          <div class="span2"><strong>Observaciones</strong></div>
          <div class="span9"><%= simple_format @quotation.observations%></div>
        </div>

      </div>
    </div>
  </body>
</html>