config/routes.rb
Logistic::Application.routes.draw do

  resources :setting_mains, except: :index


  resources :brands


  resources :areas

  resources :purchase_orders do
    member do
      put :canceled
    end
    collection do
      get :quotation_list
    end
  end

  get "site/index"

  resources :quotations do
    resource :purchase_orders
    member do
      get :fill_costs
      put :save_fill_costs
      get :toggle
      get :status_change
    end
    collection do
      get :compare
      get :pending_requeriment
    end
  end

  resources :providers

  resources :movement_items, only: [:update, :index]

  resources :movements, only: [:index, :show, :destroy] do
    member do
      get :print
    end
    collection do
      get :new_get_out_purchase_order
      get :new_purchase
      get :purchase_orders
      get :pending_incoming_purchases
      post :create_get_out_purchase_order
      post :create_purchase
      get :new_incoming
      post :create_incoming
      # get :new_get_out
      post :create_get_out
      get :pending_input_notes
    end
  end

  resources :requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :serv_requeriments do
    resources :quotations
    member do
      get :toggle
      get :status_change
    end
  end

  resources :products
  resources :groups
  resources :sub_groups
  resources :categories
  resources :brands
  resources :input_notes

  resources :ware_houses do
    get 'new_get_out' => 'movements#new_get_out'
    get 'initial' => 'movements#initial'
    get 'physical' => 'product_ware_houses#index'
    collection do
      get :own
      get :kardex
    end
  end

  resources :product_ware_houses, only: [:index, :update] do
    collection do
      put :update_multiple
    end
  end

  devise_for :users

  resources :users

  root :to => 'site#index'

  get 'dynamic_groups_by_type' => 'javascripts#dynamic_groups_by_type'
  get 'product_by_ware_house' => 'javascripts#product_by_ware_house'
  get 'products_by_ware_house' => 'javascripts#products_by_ware_house'
  get 'dynamic_sub_groups' => 'javascripts#dynamic_sub_groups'
  get 'dynamic_categories' => 'javascripts#dynamic_categories'
  get 'dynamic_products' => 'javascripts#dynamic_products'
  get 'dynamic_brands_by_group' => 'javascripts#dynamic_brands_by_group'
  get 'dynamic_brands_by_sub_group' => 'javascripts#dynamic_brands_by_sub_group'

  get 'load_other_products_from_category' => 'javascripts#load_other_products_from_category'
  get 'load_other_categories_from_sub_group' => 'javascripts#load_other_categories_from_sub_group'
  get 'load_other_sub_groups_from_group' => 'javascripts#load_other_sub_groups_from_group'
  get 'load_other_brands_from_sub_group' => 'javascripts#load_other_brands_from_sub_group'

  get 'get_product' => 'javascripts#get_product'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  include PreventDestroy::Model

  has_many :products

  attr_accessible :name, :description, :long_description, :observation, :group_id, :sub_group_id
  after_create :generate_name

  validates :description, presence: true

  prevent_destroy_if_any :products

  private

  def generate_name
    new_name = Brand.maximum(:name) || '00000000'
    self.update_column(:name, new_name.next)
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  def index
    @search = Brand.search(params[:search])
    @brands = @search.page(params[:page])
    puts "XXXX #{@brands.to_json}"
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new
    @sub_groups = []
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
    @sub_groups = SubGroup.where("group_id=?", @brand.group_id)
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: t(:data_created) }
      else
        @sub_groups = SubGroup.where("group_id=?", @brand.group_id)
        format.html { render action: "new" }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Marca fue actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.destroy
        format.html { redirect_to brands_url }
        format.json { head :no_content }
      else
        format.html { redirect_to brands_url, alert: @brand.errors.full_messages.join }
      end
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= simple_form_for(@brand, :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description, input_html: {class: 'span12'} %>
    <%= f.input :long_description, input_html: {class: 'span12'} %>

    <%= f.input :observation, input_html: {class: 'span12'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<script>var entity = "brand";</script>

app/views/brands/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Acciones</li>
      <%=nav_link('Marcas', brands_path)%>
      <%=nav_link('Nuevo', new_brand_path)%>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/brands/edit.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3 class='text-center'>Actualizar marca</h3>
	<%= render 'form' %>
</div>

app/views/brands/index.html.erb
<%=render 'sidebar'%>
<div class="span9">
    <h3 class='text-center'>Marcas</h3>

    <%=simple_form_for(@search, html: {class: 'form-search' }) do |f|%>
        <%= f.label :name_or_description_contains, "Nombre o descripción: " %>
        <%= f.text_field :name_or_description_contains, class: 'search-query'%>
        <button type="submit" class="btn">Buscar</button>
    <%end%>

    <table class="table table-striped table-hover table-condensed">
        <thead>
          <tr>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <% @brands.each do |brand| %>
              <tr>
                <td><%= brand.name %></td>
                <td><%= brand.description %></td>
                <td><%= brand.long_description %></td>
                <td><%= show_link brand %></td>
                <td><%= edit_link edit_brand_path(brand) %></td>
                <td><%= destroy_link brand %></td>
              </tr>
            <% end %>
        </tbody>
    </table>
    <%=paginate @brands%>
</div>

app/views/brands/new.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<h3 class='text'>Nueva marca</h3>
	<%= render 'form' %>
</div>

app/views/brands/show.html.erb
<%=render 'sidebar'%>
<div class="span9">
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Nombre:</b>
	  <%= @brand.name %>
	</p>

	<p>
	  <b>Descripción:</b>
	  <%= @brand.description %>
	</p>

  <%= edit_button edit_product_path(@brand) %>
	<%= destroy_button @brand %>
</div>